
openapi: 3.0.0
info: 
  title: Documentation for HedgeNest investment plan creation for only admin
  version: 1.0.0
  description: HedgeNest for  creating investment plan 
paths: 
  /api/v1/investmentPlan:
    post:
      summary: this end point is for the investment plans
      tags: [investment plan]
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - investmentName
                - roi
                - term
                - minAmount
              properties:
                investmentName: 
                  type: string
                  example: nestSafe 90
                roi:
                  type: number
                  example: 14.5
                term:
                  type: number
                  example: 90
                minAmount:
                  type: number
                  example: 5000
      responses: 
        "200":
          description: Conversion successful
        "400":
          description: something went wrong
   
    get:
      summary: this end point is to get all investment plan 
      tags: [investment plan]
      security: 
        - bearerAuth: []
      responses: 
        "201":
          description: All investments retrieved
        "400":
          description: something went wrong